version: "3.9"
services:
  server:
    command: "npm run start:server"
    build: .
    environment:
      - CHESS_DB=mongodb://mongo:27017
    ports:
      - 8050:8050/tcp
    depends_on:
      - mongo
  # client:
  #   command: "npm run start:client"
  #   build: .
  #   ports:
  #     - 3000:3000/tcp
  #   depends_on:
  #     - server
  mongo:
    image: mongo:7.0.10-rc0-jammy
